// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="s2p_s2p,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.544286,HLS_SYN_LAT=3600,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=10,HLS_SYN_LUT=239,HLS_VERSION=2022_2}" *)

module s2p (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        en_qpsk,
        en_qam16,
        en_qam64,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        input_r_TKEEP,
        input_r_TSTRB,
        input_r_TLAST,
        output1_TDATA,
        output1_TVALID,
        output1_TREADY,
        output2_TDATA,
        output2_TVALID,
        output2_TREADY,
        output3_TDATA,
        output3_TVALID,
        output3_TREADY,
        output4_TDATA,
        output4_TVALID,
        output4_TREADY,
        output5_TDATA,
        output5_TVALID,
        output5_TREADY,
        output6_TDATA,
        output6_TVALID,
        output6_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   en_qpsk;
input   en_qam16;
input   en_qam64;
input  [7:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
input  [0:0] input_r_TKEEP;
input  [0:0] input_r_TSTRB;
input  [0:0] input_r_TLAST;
output  [7:0] output1_TDATA;
output   output1_TVALID;
input   output1_TREADY;
output  [7:0] output2_TDATA;
output   output2_TVALID;
input   output2_TREADY;
output  [7:0] output3_TDATA;
output   output3_TVALID;
input   output3_TREADY;
output  [7:0] output4_TDATA;
output   output4_TVALID;
input   output4_TREADY;
output  [7:0] output5_TDATA;
output   output5_TVALID;
input   output5_TREADY;
output  [7:0] output6_TDATA;
output   output6_TVALID;
input   output6_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input_r_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] en_qpsk_read_read_fu_122_p2;
wire   [0:0] en_qam16_read_read_fu_116_p2;
wire   [0:0] en_qam64_read_read_fu_110_p2;
reg    output1_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg    output2_TDATA_blk_n;
reg    output3_TDATA_blk_n;
reg    output4_TDATA_blk_n;
reg    output5_TDATA_blk_n;
reg    output6_TDATA_blk_n;
wire   [0:0] ap_phi_mux_temp_last_V_3_phi_fu_186_p8;
reg   [0:0] temp_last_V_3_reg_182;
reg    ap_predicate_op45_read_state2;
reg    ap_predicate_op61_read_state2;
reg    ap_block_state2;
reg    ap_block_state2_io;
reg   [0:0] temp1_fu_86;
wire   [0:0] trunc_ln186_2_fu_229_p1;
wire   [0:0] trunc_ln186_1_fu_279_p1;
wire   [0:0] trunc_ln186_fu_313_p1;
reg   [0:0] ap_sig_allocacmp_temp1_1;
reg   [0:0] temp2_fu_90;
reg   [0:0] ap_sig_allocacmp_temp2_1;
reg   [0:0] temp3_fu_94;
reg   [0:0] ap_sig_allocacmp_temp3_1;
reg   [0:0] temp4_fu_98;
reg   [0:0] ap_sig_allocacmp_temp4_1;
reg   [0:0] temp5_fu_102;
reg   [0:0] ap_sig_allocacmp_temp5_1;
reg   [0:0] temp6_fu_106;
reg   [0:0] ap_sig_allocacmp_temp6_1;
wire    regslice_both_output1_U_apdone_blk;
wire    regslice_both_output2_U_apdone_blk;
wire    regslice_both_output3_U_apdone_blk;
wire    regslice_both_output4_U_apdone_blk;
wire    regslice_both_output5_U_apdone_blk;
wire    regslice_both_output6_U_apdone_blk;
reg    ap_block_state3;
reg    ap_block_state3_io;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_input_r_V_data_V_U_apdone_blk;
wire   [7:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_V_data_V_U_ack_in;
wire    regslice_both_input_r_V_keep_V_U_apdone_blk;
wire   [0:0] input_r_TKEEP_int_regslice;
wire    regslice_both_input_r_V_keep_V_U_vld_out;
wire    regslice_both_input_r_V_keep_V_U_ack_in;
wire    regslice_both_input_r_V_strb_V_U_apdone_blk;
wire   [0:0] input_r_TSTRB_int_regslice;
wire    regslice_both_input_r_V_strb_V_U_vld_out;
wire    regslice_both_input_r_V_strb_V_U_ack_in;
wire    regslice_both_input_r_V_last_V_U_apdone_blk;
wire   [0:0] input_r_TLAST_int_regslice;
wire    regslice_both_input_r_V_last_V_U_vld_out;
wire    regslice_both_input_r_V_last_V_U_ack_in;
wire   [7:0] output1_TDATA_int_regslice;
reg    output1_TVALID_int_regslice;
wire    output1_TREADY_int_regslice;
wire    regslice_both_output1_U_vld_out;
wire   [7:0] output2_TDATA_int_regslice;
reg    output2_TVALID_int_regslice;
wire    output2_TREADY_int_regslice;
wire    regslice_both_output2_U_vld_out;
wire   [7:0] output3_TDATA_int_regslice;
reg    output3_TVALID_int_regslice;
wire    output3_TREADY_int_regslice;
wire    regslice_both_output3_U_vld_out;
wire   [7:0] output4_TDATA_int_regslice;
reg    output4_TVALID_int_regslice;
wire    output4_TREADY_int_regslice;
wire    regslice_both_output4_U_vld_out;
wire   [7:0] output5_TDATA_int_regslice;
reg    output5_TVALID_int_regslice;
wire    output5_TREADY_int_regslice;
wire    regslice_both_output5_U_vld_out;
wire   [7:0] output6_TDATA_int_regslice;
reg    output6_TVALID_int_regslice;
wire    output6_TREADY_int_regslice;
wire    regslice_both_output6_U_vld_out;
reg    ap_condition_73;
reg    ap_condition_480;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
end

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_data_V_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_data_V_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TKEEP),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_keep_V_U_ack_in),
    .data_out(input_r_TKEEP_int_regslice),
    .vld_out(regslice_both_input_r_V_keep_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_keep_V_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TSTRB),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_strb_V_U_ack_in),
    .data_out(input_r_TSTRB_int_regslice),
    .vld_out(regslice_both_input_r_V_strb_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_strb_V_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TLAST),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_V_last_V_U_ack_in),
    .data_out(input_r_TLAST_int_regslice),
    .vld_out(regslice_both_input_r_V_last_V_U_vld_out),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_V_last_V_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output1_TDATA_int_regslice),
    .vld_in(output1_TVALID_int_regslice),
    .ack_in(output1_TREADY_int_regslice),
    .data_out(output1_TDATA),
    .vld_out(regslice_both_output1_U_vld_out),
    .ack_out(output1_TREADY),
    .apdone_blk(regslice_both_output1_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output2_TDATA_int_regslice),
    .vld_in(output2_TVALID_int_regslice),
    .ack_in(output2_TREADY_int_regslice),
    .data_out(output2_TDATA),
    .vld_out(regslice_both_output2_U_vld_out),
    .ack_out(output2_TREADY),
    .apdone_blk(regslice_both_output2_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output3_TDATA_int_regslice),
    .vld_in(output3_TVALID_int_regslice),
    .ack_in(output3_TREADY_int_regslice),
    .data_out(output3_TDATA),
    .vld_out(regslice_both_output3_U_vld_out),
    .ack_out(output3_TREADY),
    .apdone_blk(regslice_both_output3_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output4_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output4_TDATA_int_regslice),
    .vld_in(output4_TVALID_int_regslice),
    .ack_in(output4_TREADY_int_regslice),
    .data_out(output4_TDATA),
    .vld_out(regslice_both_output4_U_vld_out),
    .ack_out(output4_TREADY),
    .apdone_blk(regslice_both_output4_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output5_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output5_TDATA_int_regslice),
    .vld_in(output5_TVALID_int_regslice),
    .ack_in(output5_TREADY_int_regslice),
    .data_out(output5_TDATA),
    .vld_out(regslice_both_output5_U_vld_out),
    .ack_out(output5_TREADY),
    .apdone_blk(regslice_both_output5_U_apdone_blk)
);

s2p_regslice_both #(
    .DataWidth( 8 ))
regslice_both_output6_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output6_TDATA_int_regslice),
    .vld_in(output6_TVALID_int_regslice),
    .ack_in(output6_TREADY_int_regslice),
    .data_out(output6_TDATA),
    .vld_out(regslice_both_output6_U_vld_out),
    .ack_out(output6_TREADY),
    .apdone_blk(regslice_both_output6_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_480)) begin
        if ((en_qpsk_read_read_fu_122_p2 == 1'd1)) begin
            temp1_fu_86 <= trunc_ln186_fu_313_p1;
        end else if (((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0))) begin
            temp1_fu_86 <= trunc_ln186_1_fu_279_p1;
        end else if ((1'b1 == ap_condition_73)) begin
            temp1_fu_86 <= trunc_ln186_2_fu_229_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        temp3_fu_94 <= 1'd0;
    end else if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp3_fu_94 <= input_r_TDATA_int_regslice[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        temp4_fu_98 <= 1'd0;
    end else if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp4_fu_98 <= input_r_TDATA_int_regslice[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp5_fu_102 <= 1'd0;
    end else if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        temp5_fu_102 <= input_r_TDATA_int_regslice[32'd4];
    end
end

always @ (posedge ap_clk) begin
    if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp6_fu_106 <= 1'd0;
    end else if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        temp6_fu_106 <= input_r_TDATA_int_regslice[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd0) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        temp_last_V_3_reg_182 <= 1'd0;
    end else if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp_last_V_3_reg_182 <= input_r_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp2_fu_90 <= input_r_TDATA_int_regslice[32'd1];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io)) & (1'b1 == ap_CS_fsm_state3) & (ap_phi_mux_temp_last_V_3_phi_fu_186_p8 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io)) & (1'b1 == ap_CS_fsm_state3) & (ap_phi_mux_temp_last_V_3_phi_fu_186_p8 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if ((en_qpsk_read_read_fu_122_p2 == 1'd1)) begin
            ap_sig_allocacmp_temp1_1 = trunc_ln186_fu_313_p1;
        end else if (((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0))) begin
            ap_sig_allocacmp_temp1_1 = trunc_ln186_1_fu_279_p1;
        end else if ((1'b1 == ap_condition_73)) begin
            ap_sig_allocacmp_temp1_1 = trunc_ln186_2_fu_229_p1;
        end else begin
            ap_sig_allocacmp_temp1_1 = temp1_fu_86;
        end
    end else begin
        ap_sig_allocacmp_temp1_1 = temp1_fu_86;
    end
end

always @ (*) begin
    if ((((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_sig_allocacmp_temp2_1 = input_r_TDATA_int_regslice[32'd1];
    end else begin
        ap_sig_allocacmp_temp2_1 = temp2_fu_90;
    end
end

always @ (*) begin
    if (((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_sig_allocacmp_temp3_1 = 1'd0;
    end else if ((((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_sig_allocacmp_temp3_1 = input_r_TDATA_int_regslice[32'd2];
    end else begin
        ap_sig_allocacmp_temp3_1 = temp3_fu_94;
    end
end

always @ (*) begin
    if (((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_sig_allocacmp_temp4_1 = 1'd0;
    end else if ((((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_sig_allocacmp_temp4_1 = input_r_TDATA_int_regslice[32'd3];
    end else begin
        ap_sig_allocacmp_temp4_1 = temp4_fu_98;
    end
end

always @ (*) begin
    if ((((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_sig_allocacmp_temp5_1 = 1'd0;
    end else if (((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_sig_allocacmp_temp5_1 = input_r_TDATA_int_regslice[32'd4];
    end else begin
        ap_sig_allocacmp_temp5_1 = temp5_fu_102;
    end
end

always @ (*) begin
    if ((((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_sig_allocacmp_temp6_1 = 1'd0;
    end else if (((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_sig_allocacmp_temp6_1 = input_r_TDATA_int_regslice[32'd5];
    end else begin
        ap_sig_allocacmp_temp6_1 = temp6_fu_106;
    end
end

always @ (*) begin
    if ((((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (en_qpsk_read_read_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op61_read_state2 == 1'b1)) | (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op45_read_state2 == 1'b1)))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output1_TDATA_blk_n = output1_TREADY_int_regslice;
    end else begin
        output1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output1_TVALID_int_regslice = 1'b1;
    end else begin
        output1_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output2_TDATA_blk_n = output2_TREADY_int_regslice;
    end else begin
        output2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output2_TVALID_int_regslice = 1'b1;
    end else begin
        output2_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output3_TDATA_blk_n = output3_TREADY_int_regslice;
    end else begin
        output3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output3_TVALID_int_regslice = 1'b1;
    end else begin
        output3_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output4_TDATA_blk_n = output4_TREADY_int_regslice;
    end else begin
        output4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output4_TVALID_int_regslice = 1'b1;
    end else begin
        output4_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output5_TDATA_blk_n = output5_TREADY_int_regslice;
    end else begin
        output5_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output5_TVALID_int_regslice = 1'b1;
    end else begin
        output5_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        output6_TDATA_blk_n = output6_TREADY_int_regslice;
    end else begin
        output6_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
        output6_TVALID_int_regslice = 1'b1;
    end else begin
        output6_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io)) & (1'b1 == ap_CS_fsm_state3) & (ap_phi_mux_temp_last_V_3_phi_fu_186_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io)) & (1'b1 == ap_CS_fsm_state3) & (ap_phi_mux_temp_last_V_3_phi_fu_186_p8 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2 = ((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_io = ((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (regslice_both_output6_U_apdone_blk == 1'b1) | (regslice_both_output5_U_apdone_blk == 1'b1) | (regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_block_state3_io = ((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_480 = (~((output6_TREADY_int_regslice == 1'b0) | (output5_TREADY_int_regslice == 1'b0) | (output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (output2_TREADY_int_regslice == 1'b0) | (output1_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state2_io) | ((en_qpsk_read_read_fu_122_p2 == 1'd1) & (input_r_TVALID_int_regslice == 1'b0)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op61_read_state2 == 1'b1)) | ((input_r_TVALID_int_regslice == 1'b0) & (ap_predicate_op45_read_state2 == 1'b1))) & (1'b1 == ap_CS_fsm_state2));
end

always @ (*) begin
    ap_condition_73 = ((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0));
end

assign ap_phi_mux_temp_last_V_3_phi_fu_186_p8 = temp_last_V_3_reg_182;

always @ (*) begin
    ap_predicate_op45_read_state2 = ((en_qam64_read_read_fu_110_p2 == 1'd1) & (en_qam16_read_read_fu_116_p2 == 1'd0) & (en_qpsk_read_read_fu_122_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op61_read_state2 = ((en_qam16_read_read_fu_116_p2 == 1'd1) & (en_qpsk_read_read_fu_122_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign en_qam16_read_read_fu_116_p2 = en_qam16;

assign en_qam64_read_read_fu_110_p2 = en_qam64;

assign en_qpsk_read_read_fu_122_p2 = en_qpsk;

assign input_r_TREADY = regslice_both_input_r_V_data_V_U_ack_in;

assign output1_TDATA_int_regslice = ap_sig_allocacmp_temp1_1;

assign output1_TVALID = regslice_both_output1_U_vld_out;

assign output2_TDATA_int_regslice = ap_sig_allocacmp_temp2_1;

assign output2_TVALID = regslice_both_output2_U_vld_out;

assign output3_TDATA_int_regslice = ap_sig_allocacmp_temp3_1;

assign output3_TVALID = regslice_both_output3_U_vld_out;

assign output4_TDATA_int_regslice = ap_sig_allocacmp_temp4_1;

assign output4_TVALID = regslice_both_output4_U_vld_out;

assign output5_TDATA_int_regslice = ap_sig_allocacmp_temp5_1;

assign output5_TVALID = regslice_both_output5_U_vld_out;

assign output6_TDATA_int_regslice = ap_sig_allocacmp_temp6_1;

assign output6_TVALID = regslice_both_output6_U_vld_out;

assign trunc_ln186_1_fu_279_p1 = input_r_TDATA_int_regslice[0:0];

assign trunc_ln186_2_fu_229_p1 = input_r_TDATA_int_regslice[0:0];

assign trunc_ln186_fu_313_p1 = input_r_TDATA_int_regslice[0:0];

endmodule //s2p
